// Helpers for generating League of Legends spectator launch scripts.
//
// When a player is in a live game, Riot's spectator-v5 endpoint returns
// the encryption credentials needed to connect to the spectator stream.
// We bundle those credentials into a small script (a .bat for Windows,
// a .command for macOS) that the user downloads and runs. The script
// invokes their local League client with the spectator arguments,
// launching them straight into the live match as an observer.
//
// Same approach used by OP.GG, U.GG, and lolspectator.tv.
//
// Sources: lolspectator.tv production scripts (2025), Riot dev-relations
// issue #892 (spectator host info as of patch 14.x).

import type { Platform } from './regions';

// Spectator hosts vary by region. These are the modern endpoints used by
// the Riot client itself when launching spectator mode. Format:
//   <host>:<port>
// Note that some smaller regions share spectator hosts (e.g. EUNE shares
// EUW's, BR shares LAN's) which is normal — the platform ID inside the
// command line tells the spectator server which game to look up.
export const SPECTATOR_HOSTS: Record<Platform, { host: string; port: number; platformId: string }> = {
  na1:  { host: 'spectator-consumer.na.lol.pvp.net',  port: 80, platformId: 'NA1' },
  euw1: { host: 'spectator-consumer.euw1.lol.pvp.net', port: 80, platformId: 'EUW1' },
  eun1: { host: 'spectator-consumer.eun1.lol.pvp.net', port: 80, platformId: 'EUN1' },
  kr:   { host: 'spectator-consumer.kr.lol.pvp.net',   port: 80, platformId: 'KR' },
  jp1:  { host: 'spectator-consumer.jp1.lol.pvp.net',  port: 80, platformId: 'JP1' },
  br1:  { host: 'spectator-consumer.br1.lol.pvp.net',  port: 80, platformId: 'BR1' },
  la1:  { host: 'spectator-consumer.la1.lol.pvp.net',  port: 80, platformId: 'LA1' },
  la2:  { host: 'spectator-consumer.la2.lol.pvp.net',  port: 80, platformId: 'LA2' },
  oc1:  { host: 'spectator-consumer.oc1.lol.pvp.net',  port: 80, platformId: 'OC1' },
  tr1:  { host: 'spectator-consumer.tr1.lol.pvp.net',  port: 80, platformId: 'TR1' },
  ru:   { host: 'spectator-consumer.ru.lol.pvp.net',   port: 80, platformId: 'RU' },
};

/** Information needed to build a spectator script. */
export interface SpectateInfo {
  region: Platform;
  /** Numeric Riot game ID (CurrentGame.gameId). */
  gameId: number;
  /** Base64 encryption key (CurrentGame.observers.encryptionKey). */
  encryptionKey: string;
}

/**
 * Build the Windows .bat script content.
 *
 * Default install path is "C:\Riot Games\League of Legends\Game". If the
 * user has installed elsewhere they'll need to edit the script — we
 * include a comment about this.
 */
export function buildBatScript(info: SpectateInfo): string {
  const hostCfg = SPECTATOR_HOSTS[info.region];
  if (!hostCfg) {
    throw new Error(`Unknown spectator region: ${info.region}`);
  }
  const { host, port, platformId } = hostCfg;
  const args = `spectator ${host}:${port} ${info.encryptionKey} ${info.gameId} ${platformId}`;
  // The "-UseRads" flag is required by older League launchers and harmless
  // on newer ones. Both lolspectator.tv and Mobalytics include it.
  return [
    '@echo off',
    'REM Spectator launch script generated by lol-statss',
    'REM',
    'REM If your League of Legends folder is NOT in C:\\Riot Games\\,',
    'REM edit the path on the next line accordingly.',
    'REM',
    'cd /d "C:\\Riot Games\\League of Legends\\Game" & "League of Legends.exe" "' + args + '" "-UseRads"',
    '',
  ].join('\r\n');
}

/**
 * Build the macOS .command script content. Made executable by the
 * download handler (we set the right Content-Disposition).
 */
export function buildMacScript(info: SpectateInfo): string {
  const hostCfg = SPECTATOR_HOSTS[info.region];
  if (!hostCfg) {
    throw new Error(`Unknown spectator region: ${info.region}`);
  }
  const { host, port, platformId } = hostCfg;
  const args = `spectator ${host}:${port} ${info.encryptionKey} ${info.gameId} ${platformId}`;
  return [
    '#!/bin/bash',
    '# Spectator launch script generated by lol-statss',
    '# If League is installed elsewhere, edit the cd path below.',
    'cd "/Applications/League of Legends.app/Contents/LoL/Game" || exit 1',
    `./LeagueofLegends.app/Contents/MacOS/LeagueofLegends "${args}" "-UseRads"`,
    '',
  ].join('\n');
}

/** True if we know how to spectate this region. */
export function canSpectate(region: Platform): boolean {
  return region in SPECTATOR_HOSTS;
}
